services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recycling_monitor_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true